version: "3.8"
services:

  # database application service
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db:/var/lib/mysql

    # backend application service
  achat-backend:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - 8087:8087




    stdin_open: true
    tty: true
    environment:



      SPRING APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/invoicedb?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": null,
        "spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
  # Frontend application service
  front:
    image: dhiatrabelsi/front:15
    ports:
      - "86:86"

volumes:
  db :