version: "3.8"
services:
  mysql-db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=devops
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  devops-app:
    image: rayan1512/devopsproject
    depends_on:
      - mysql-db
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
             "spring.datasource.url": "jdbc:mysql://mysql-db:3307/devops?allowPublicKeyRetrieval=true&useSSL=false",
            "spring.datasource.username": "root",
            "spring.datasource.password": "",
            "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5Dialect",
            "spring.jpa.hibernate.ddl-auto": "update"
          }'
    ports:
      - "8082:8082"

volumes:
  db-data:
