apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Ce type te permet d'exposer ton frontend en externe
