apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskgpt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskgpt
  template:
    metadata:
      labels:
        app: flaskgpt
    spec:
      containers:
        - name: flaskgpt
          image: roua863/devops:latest  # Utilise l'image que tu as déjà créée
          ports:
            - containerPort: 5000  # Assure-toi que c'est le port utilisé par ton application Flask
